export const CATEGORIES = [
  { id: 'all', name: 'All Medicines' },
  { id: 'chronic', name: 'Chronic Care' },
  { id: 'fever', name: 'Fever & Pain' },
  { id: 'infection', name: 'Infections' },
  { id: 'supplements', name: 'Supplements' },
  { id: 'skincare', name: 'Skincare' },
  { id: 'diabetes', name: 'Diabetes' },
  { id: 'heart', name: 'Heart Health' }
];

export const MEDICINES = [
  {
    id: 'm1',
    name: 'Panadol Extra',
    brand: 'GSK',
    formula: 'Paracetamol + Caffeine',
    salt: 'Paracetamol 500mg, Caffeine 65mg',
    price: 35,
    category: 'fever',
    description: 'Powerful relief for tough pain, including migraine, headache, and toothache.',
    strength: '500mg/65mg',
    stock: 1200,
    rating: 4.8,
    reviews: 124,
    sideEffects: ['Restlessness', 'Insomnia', 'Increased heart rate'],
    usage: 'Take 1-2 tablets every 4-6 hours. Do not exceed 8 tablets in 24 hours.',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=300&auto=format&fit=crop',
    tags: ['fever', 'pain', 'headache', 'body ache', 'migraine']
  },
  {
    id: 'm2',
    name: 'Glucophage',
    brand: 'Merck',
    formula: 'Metformin Hydrochloride',
    salt: 'Metformin HCl',
    price: 180,
    category: 'diabetes',
    description: 'First-line medication for the treatment of type 2 diabetes.',
    strength: '500mg',
    stock: 800,
    rating: 4.9,
    reviews: 89,
    sideEffects: ['Nausea', 'Stomach upset', 'Metallic taste'],
    usage: 'Take with meals to reduce stomach side effects. Follow doctor prescription.',
    image: 'https://images.unsplash.com/photo-1550572017-ed20bb0029b3?q=80&w=300&auto=format&fit=crop',
    tags: ['diabetes', 'sugar', 'blood sugar', 'insulin']
  },
  {
    id: 'm3',
    name: 'Augmentin 625',
    brand: 'GSK',
    formula: 'Amoxicillin + Clavulanate Potassium',
    salt: 'Co-amoxiclav',
    price: 650,
    category: 'infection',
    description: 'Broad-spectrum antibiotic used to treat various bacterial infections.',
    strength: '625mg',
    stock: 150,
    rating: 4.7,
    reviews: 210,
    sideEffects: ['Diarrhea', 'Thrush', 'Nausea'],
    usage: 'Complete the full course as prescribed by your doctor.',
    image: 'https://images.unsplash.com/photo-1471864190281-ad5f9fc0724c?q=80&w=300&auto=format&fit=crop',
    tags: ['infection', 'antibiotic', 'throat', 'bacterial', 'fever']
  },
  {
    id: 'm4',
    name: 'Lipiget 20',
    brand: 'Getz Pharma',
    formula: 'Atorvastatin',
    salt: 'Atorvastatin Calcium',
    price: 340,
    category: 'heart',
    description: 'Statins used for lowering high cholesterol and triglyceride levels.',
    strength: '20mg',
    stock: 500,
    rating: 4.6,
    reviews: 56,
    sideEffects: ['Muscle pain', 'Joint pain', 'Nausea'],
    usage: 'Usually taken once a day, with or without food.',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?q=80&w=300&auto=format&fit=crop',
    tags: ['cholesterol', 'heart', 'bp', 'blood pressure', 'statin']
  },
  {
    id: 'm5',
    name: 'Nexum',
    brand: 'Getz Pharma',
    formula: 'Esomeprazole',
    salt: 'Esomeprazole Magnesium',
    price: 380,
    category: 'chronic',
    description: 'Proton pump inhibitor that decreases stomach acid production.',
    strength: '400mg',
    stock: 450,
    rating: 4.8,
    reviews: 142,
    sideEffects: ['Headache', 'Dry mouth', 'Abdominal pain'],
    usage: 'Take at least 1 hour before a meal.',
    image: 'https://images.unsplash.com/photo-1512428559083-a436df4d2716?q=80&w=300&auto=format&fit=crop',
    tags: ['stomach', 'acid', 'heartburn', 'gastric', 'ulcer']
  },
  {
    id: 'm6',
    name: 'Gaviscon Liquid',
    brand: 'Reckitt',
    formula: 'Sodium Alginate + Sodium Bicarbonate',
    salt: 'Anti-acid formula',
    price: 250,
    category: 'chronic',
    description: 'Fast relief from heartburn and acid reflux.',
    strength: '150ml',
    stock: 300,
    rating: 4.9,
    reviews: 320,
    sideEffects: ['Constipation', 'Bloating'],
    usage: 'Shake well before use. Take after meals and at bedtime.',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b340e7a5?q=80&w=300&auto=format&fit=crop',
    tags: ['heartburn', 'acid', 'reflux', 'digestion', 'stomach']
  },
  {
    id: 'm7',
    name: 'Ventolin Inhaler',
    brand: 'GSK',
    formula: 'Salbutamol',
    salt: 'Salbutamol Sulfate',
    price: 480,
    category: 'chronic',
    description: 'Relieves symptoms of asthma and COPD.',
    strength: '100mcg',
    stock: 200,
    rating: 4.9,
    reviews: 450,
    sideEffects: ['Tremor', 'Headache', 'Tachycardia'],
    usage: 'Use as directed during asthma attacks or before exercise.',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?q=80&w=300&auto=format&fit=crop',
    tags: ['asthma', 'breathing', 'cough', 'lung']
  },
  {
    id: 'm8',
    name: 'Laroscorbine',
    brand: 'Bayer',
    formula: 'Vitamin C + Zinc',
    salt: 'Ascorbic Acid + Zinc',
    price: 1200,
    category: 'supplements',
    description: 'Effervescent tablets for immune system support.',
    strength: '1000mg',
    stock: 100,
    rating: 4.8,
    reviews: 180,
    sideEffects: ['Stomach cramps', 'Heartburn'],
    usage: 'Dissolve one tablet in a glass of water daily.',
    image: 'https://images.unsplash.com/photo-1616671285410-998801538965?q=80&w=300&auto=format&fit=crop',
    tags: ['immune', 'vitamin', 'energy', 'flu', 'cold']
  },
  {
    id: 'm9',
    name: 'Surbex-Z',
    brand: 'Abbott',
    formula: 'Multivitamins + Zinc',
    salt: 'Vitamin B-Complex + Zinc',
    price: 450,
    category: 'supplements',
    description: 'Energy-boosting multivitamin with high-potency zinc.',
    strength: '30 Tablets',
    stock: 600,
    rating: 4.7,
    reviews: 290,
    sideEffects: ['Nausea', 'Bad taste'],
    usage: 'One tablet daily with food.',
    image: 'https://images.unsplash.com/photo-1471864190281-ad5f9fc0724c?q=80&w=300&auto=format&fit=crop',
    tags: ['vitamin', 'multivitamin', 'energy', 'health', 'fitness']
  },
  {
    id: 'm10',
    name: 'CeraVe Hydrating',
    brand: 'L-Oreal',
    formula: 'Ceramides + Hyaluronic Acid',
    salt: 'Gentle Cleanser',
    price: 3200,
    category: 'skincare',
    description: 'Developed with dermatologists, a gentle non-foaming cleanser.',
    strength: '236ml',
    stock: 80,
    rating: 5.0,
    reviews: 1200,
    sideEffects: ['None reported'],
    usage: 'Wet skin with lukewarm water. Massage cleanser into skin.',
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=300&auto=format&fit=crop',
    tags: ['skincare', 'dry skin', 'cleanser', 'face']
  },
  {
    id: 'm11',
    name: 'Calpol 500',
    brand: 'GSK',
    formula: 'Paracetamol',
    salt: 'Paracetamol',
    price: 30,
    category: 'fever',
    description: 'Relief of mild to moderate pain and fever.',
    strength: '500mg',
    stock: 2000,
    rating: 4.6,
    reviews: 45,
    sideEffects: ['Rare allergic reactions'],
    usage: 'Take 1-2 tablets for fever relief.',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=300&auto=format&fit=crop',
    tags: ['fever', 'pain', 'headache', 'child care']
  },
  {
    id: 'm12',
    name: 'Esodif 40',
    brand: 'High-Q',
    formula: 'Esomeprazole',
    salt: 'Esomeprazole Sodium',
    price: 360,
    category: 'chronic',
    description: 'Inhibits gastric acid secretion for gastric ulcer treatment.',
    strength: '40mg',
    stock: 400,
    rating: 4.7,
    reviews: 28,
    sideEffects: ['Headache', 'Vomiting'],
    usage: 'Take once daily before breakfast.',
    image: 'https://images.unsplash.com/photo-1512428559083-a436df4d2716?q=80&w=300&auto=format&fit=crop',
    tags: ['stomach', 'acid', 'gastric', 'ulcer']
  },
  {
    id: 'm13',
    name: 'Atorva 20',
    brand: 'Abbott',
    formula: 'Atorvastatin',
    salt: 'Atorvastatin Calcium',
    price: 320,
    category: 'heart',
    description: 'Lowers bad cholesterol and raises good cholesterol.',
    strength: '20mg',
    stock: 600,
    rating: 4.5,
    reviews: 19,
    sideEffects: ['Muscle weakness'],
    usage: 'One tablet at night.',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?q=80&w=300&auto=format&fit=crop',
    tags: ['cholesterol', 'heart', 'bp', 'statin']
  }
];

export const doctors = [
  {
    id: "dr1",
    name: "Dr. Sarah Ahmed",
    specialty: "Senior Pharmacist",
    experience: "12 Years",
    rating: 4.9,
    status: "Online",
    image: "https://i.pravatar.cc/150?u=sarah",
    availability: "Immediate",
    fees: "500",
    description: "Expert in medication management and drug interactions. Specializes in chronic care counseling."
  },
  {
    id: "dr2",
    name: "Dr. Ali Raza",
    specialty: "General Physician",
    experience: "8 Years",
    rating: 4.7,
    status: "Online",
    image: "https://i.pravatar.cc/150?u=ali",
    availability: "In 15 mins",
    fees: "1000",
    description: "Primary care specialist with focus on family medicine and preventive aesthetics."
  },
  {
    id: "dr3",
    name: "Dr. Zainab Khan",
    specialty: "Nutritionist",
    experience: "5 Years",
    rating: 4.8,
    status: "Offline",
    image: "https://i.pravatar.cc/150?u=zainab",
    availability: "Tomorrow 10 AM",
    fees: "800",
    description: "Certified nutritionist helping patients manage diabetes and heart health through diet."
  }
];

export const STAFF = [
  { 
    id: 's1', 
    name: 'Zeeshan Khan', 
    role: 'Pharmacist', 
    status: 'Active', 
    ordersCompleted: 145, 
    shift: '09:00 AM - 05:00 PM',
    checkIn: '08:52 AM',
    checkOut: '-',
    performance: 98,
    contact: '+92 300 1234567',
    avatar: 'https://i.pravatar.cc/150?u=s1'
  },
  { 
    id: 's2', 
    name: 'Ayesha Malik', 
    role: 'Packer', 
    status: 'Active', 
    ordersCompleted: 328, 
    shift: '08:00 AM - 04:00 PM',
    checkIn: '07:55 AM',
    checkOut: '-',
    performance: 95,
    contact: '+92 301 7654321',
    avatar: 'https://i.pravatar.cc/150?u=s2'
  },
  { 
    id: 's3', 
    name: 'Hamza Farooq', 
    role: 'Rider', 
    status: 'Busy', 
    ordersCompleted: 189, 
    shift: '12:00 PM - 08:00 PM',
    checkIn: '11:45 AM',
    checkOut: '-',
    performance: 92,
    contact: '+92 305 2223334',
    avatar: 'https://i.pravatar.cc/150?u=s3'
  },
  { 
    id: 's4', 
    name: 'Saba Ahmed', 
    role: 'Staff', 
    status: 'Away', 
    ordersCompleted: 12, 
    shift: '09:00 AM - 05:00 PM',
    checkIn: '08:58 AM',
    checkOut: '02:30 PM (Doctor Visit)',
    performance: 88,
    contact: '+92 309 8887776',
    avatar: 'https://i.pravatar.cc/150?u=s4'
  },
  { 
    id: 's5', 
    name: 'Bilal Raza', 
    role: 'Rider', 
    status: 'Active', 
    ordersCompleted: 76, 
    shift: '06:00 PM - 02:00 AM',
    checkIn: '-',
    checkOut: '-',
    performance: 94,
    contact: '+92 312 9990001',
    avatar: 'https://i.pravatar.cc/150?u=s5'
  },
];

export const ORDERS = [
  { id: 'ORD-701', customer: 'Ali Hassan', items: 3, total: 1240, status: 'Pending', time: '10 mins ago', assignedTo: null },
  { id: 'ORD-702', customer: 'Sana Khan', items: 1, total: 450, status: 'Packed', time: '25 mins ago', assignedTo: 's2' },
  { id: 'ORD-703', customer: 'Imran Sahab', items: 5, total: 3200, status: 'Shipped', time: '1 hour ago', assignedTo: 's3' },
  { id: 'ORD-704', customer: 'John Doe', items: 2, total: 800, status: 'Delivered', time: '3 hours ago', assignedTo: 's3' },
];
